package STEAMproj;
import java.applet.AudioClip;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.image.BufferedImage;

import javax.imageio.ImageIO;
import javax.swing.JApplet;
import javax.swing.JPanel;
import javax.swing.Timer;

public class GamePanel extends JPanel implements ActionListener, KeyListener {
	Font titleFont;
	Timer frameDraw;
	Timer alienSpawn;
	//this class does formatting and creates text
	public static BufferedImage image;
	public static boolean needImage = true;
	public static boolean gotImage = false;
	final int MENU = 0;
	//intitializing the ship
	Rocketship ship = new Rocketship(250, 700, 50, 50, 10);
	final int GAME = 1;
	//manager uses the object manager to control different cases
	ObjectManager manager = new ObjectManager(ship);
	final int END = 2;
	//current states are used to flip between start game and end
	int currentState = MENU;
//text will have an intro and outro page
	public GamePanel() {
		if (needImage) {
			loadImage("space.png");
		}
		titleFont = new Font("Monospaced", Font.PLAIN, 32);
		frameDraw = new Timer(1000 / 60, this);
		frameDraw.start();
	}
//paint component draws the pages based on the currentState
	@Override
	public void paintComponent(Graphics g) {
		if (currentState == MENU) {
			drawMenuState(g);
		} else if (currentState == GAME) {
			drawGameState(g);
			
			
		} else if (currentState == END) {
			drawEndState(g);
		}
	}



	void updateMenuState() {

	}
//isActive is used to show if a rocket is alive and moving or obsolete
	void updateGameState() {
		manager.update();
	if (manager.rocket.isActive == false) {
			currentState = END;
			
		}
	}

	void updateEndState() {

	}
//this is the first page that will show
	void drawMenuState(Graphics g) {
		g.setColor(Color.BLUE);
		g.fillRect(0, 0, Invaders.WIDTH, Invaders.HEIGHT);
		g.setFont(titleFont);
		g.setColor(Color.WHITE);
		g.drawString("Space Invaders", 0, 50);

		g.setFont(titleFont);
		g.setColor(Color.WHITE);
		g.drawString("Press ENTER to Start", 0, 400);

	
	}
//tgis is the main game page
	void drawGameState(Graphics g) {
		if (gotImage) {
			g.drawImage(image, 0, 0, Invaders.WIDTH, Invaders.HEIGHT, null);
			manager.draw(g);
			
		} else {
			g.setColor(Color.BLACK);
			g.fillRect(0, 0, Invaders.WIDTH, Invaders.HEIGHT);

		}
		
	}
//this shows the score/amount of aliens killed
	void drawEndState(Graphics g) {
		g.setColor(Color.RED);
		g.fillRect(0, 0, Invaders.WIDTH, Invaders.HEIGHT);

		g.setFont(titleFont);
		g.setColor(Color.BLACK);
		g.drawString("Space Invaders", 0, 50);

		g.setFont(titleFont);
		g.setColor(Color.BLACK);
		g.drawString("You killed " + manager.getScore() + " aliens", 0, 400);

		g.setFont(titleFont);
		g.setColor(Color.BLACK);
		g.drawString("Press ENTER to start", 0, 600);
	}
//this can load the rocket, alien, and projectile pictures when called
	void loadImage(String imageFile) {
		if (needImage) {
			try {
				image = ImageIO.read(this.getClass().getResourceAsStream(imageFile));
				gotImage = true;
			} catch (Exception e) {

			}
			needImage = false;
		}
	}
//shows when something happens and calls repaint for movement
	@Override
	public void actionPerformed(ActionEvent e) {

		// TODO Auto-generated method stub
		if (currentState == MENU) {
			updateMenuState();

		} else if (currentState == GAME) {
			
			updateGameState();
		} else if (currentState == END) {
			updateEndState();
			
	
		}
		System.out.println("action");
		repaint();

	}
//next controls are for when buttons are pressed using mouselistener
	//todo auto-genereated methods are automatically made when I type in a part of the line and the rest is generated by the computer
	//ship and alienspawn don't work because the alien, rocketship, and projectile classes are still in the process of being made
	@Override
	public void keyTyped(KeyEvent e) {
		// TODO Auto-generated method stub

	}

	@Override
	public void keyPressed(KeyEvent e) {
		// TODO Auto-generated method stub

		if (e.getKeyCode() == KeyEvent.VK_ENTER) {
			if (currentState == END) {
				endGame();
		
				ship = new Rocketship(250, 700, 50, 50, 10);
				manager = new ObjectManager(ship); 
				manager.score=0;
				
	
				currentState=GAME;
				startGame();
			} else {
				currentState++;
				if (currentState == GAME) {
					startGame();
					
				}
			
			
			}
		}
		
			
		if (e.getKeyCode() == KeyEvent.VK_UP) {
			System.out.println("UP");
			if (ship.y >= 5) {
				ship.up();
			}

		}
		if (e.getKeyCode() == KeyEvent.VK_DOWN) {
			System.out.println("DOWN");

			if (ship.y <= 750) {
				ship.down();
			}

		}
		if (e.getKeyCode() == KeyEvent.VK_LEFT) {
			System.out.println("LEFT");
			if (ship.x >= 5) {
				ship.left();

			}
		}
		if (e.getKeyCode() == KeyEvent.VK_RIGHT) {
			System.out.println("RIGHT");
			if (ship.x <= 450) {

				ship.right();

			}

		}
		if (e.getKeyCode() == KeyEvent.VK_SPACE) {
			newProjectile();
		}
	}

	@Override
	public void keyReleased(KeyEvent e) {
		// TODO Auto-generated method stub

	}

	public void pew() {
		try {
		    AudioClip sound = JApplet.newAudioClip(getClass().getResource("pew.wav"));
		    sound.play();
			Thread.sleep(3400);
		} catch (Exception ex) {
			ex.printStackTrace();
		}
	}
	
	public void startGame() {
		alienSpawn = new Timer(1000, manager);
		alienSpawn.start();
		pew();
	}

	public void endGame() {
		alienSpawn.stop();
		
	}
	public void newProjectile() {
		if (currentState == GAME) {
			manager.addProjectile(ship.getProjectile());
			System.out.println();
		}
	
	}

}
